---
    - name: install HAProxy Packages
      sudo: yes
      apt: 
       name={{ item }} 
       state=present 
       update_cache=yes
      with_items:
           - haproxy
    - systemd: state=started name=haproxy enabled=yes

    - name: create front-end config
      sudo: yes
      template: src=front-end.j2 dest=/etc/haproxy/haproxy.cfg mode=0777
      notify:
      - restart haproxy

