---
    - name: install HAProxy Packages
      sudo: yes
      apt: 
       name={{ item }} 
       state=present 
       update_cache=yes
      with_items:
           - haproxy

    - name: create front-end config
      become: yes
      become_user: root
      template: src=front-end.j2 dest=/etc/haproxy/haproxy.cfg mode=0777
      notify:
        - restart haproxy
