---
    - name: install OpenCart requirement Packages
      sudo: yes
      apt: 
       name={{ item }} 
       state=present 
       update_cache=yes
      with_items:
           - apache2
           - php7.0-mysql 
           - php7.0-curl 
           - php7.0-json 
           - php7.0-cgi 
           - php7.0 
           - libapache2-mod-php7.0 
           - php7.0-mcrypt
           - php7.0-mysqli
           - php7.0-gd
           - libjpeg-dev
           - libfreetype6-dev
           - php-mysql

    - name:
      file:
       path: /tmp/opencart
       state: directory
       mode: 0777

    - name: Download OpenCart zip file
      unarchive:
        src: templates/opencart-html.zip
        dest: /tmp/opencart
        remote_src: no
        mode: 0777

    - name: rsync files
      sudo: yes
      command: rsync -Wag /tmp/opencart/upload/ /var/www/html/

    - name: Deploy config.php from config.php.j2 Template
      sudo: yes
      template: src=config.php.j2 dest=/var/www/html/config.php mode=0777

    - name: Deploy /admin/config.php from adminconfig.php.j2 Template
      become: yes
      template: src=adminconfig.php.j2 dest=/var/www/html/admin/config.php mode=0777
 
    - name: delete index.html so httpd serves index.php instead
      file:
       path: /var/www/html/index.html
       state: absent

    - name: restart apache
      become: yes
      service:
       name: apache2
       state: restarted
       enabled: yes
